# Generated by Django 5.2.17 on 2026-09-09 07:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('crs_epsg', models.PositiveIntegerField()),
                ('chainage_bearing', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coordinate_type', models.CharField(choices=[('design', 'Design'), ('as_built', 'As-built')], max_length=16)),
                ('filename', models.CharField(max_length=255)),
                ('total_rows', models.PositiveIntegerField()),
                ('created_count', models.PositiveIntegerField()),
                ('updated_count', models.PositiveIntegerField()),
                ('changed_count', models.PositiveIntegerField()),
                ('errored_count', models.PositiveIntegerField()),
                ('report', models.JSONField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_runs', to='registry.package')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('viaduct', 'Viaduct'), ('station', 'Station')], max_length=16)),
                ('ref', models.CharField(max_length=32)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='structures', to='registry.package')),
            ],
        ),
        migrations.CreateModel(
            name='PileCap',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ref', models.CharField(max_length=32)),
                ('cap_type', models.CharField(choices=[('standard', 'Standard'), ('straddle', 'Straddle')], max_length=16)),
                ('top_level', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pile_caps', to='registry.structure')),
            ],
        ),
        migrations.CreateModel(
            name='Pile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=4)),
                ('pile_no', models.CharField(max_length=32, unique=True)),
                ('diameter_mm', models.PositiveSmallIntegerField()),
                ('design_length_m', models.DecimalField(decimal_places=3, max_digits=6)),
                ('design_e', models.DecimalField(decimal_places=3, max_digits=12)),
                ('design_n', models.DecimalField(decimal_places=3, max_digits=12)),
                ('asbuilt_e', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('asbuilt_n', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('asbuilt_z', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('cutoff_level', models.DecimalField(decimal_places=3, max_digits=8)),
                ('tip_elevation', models.DecimalField(decimal_places=3, max_digits=8)),
                ('concreting_finished_at', models.DateTimeField(blank=True, null=True)),
                ('asbuilt_run', models.ForeignKey(blank=True, help_text='The as_built ImportRun that last matched this pile.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='registry.importrun')),
                ('created_by_run', models.ForeignKey(blank=True, help_text='The design ImportRun that created this pile. Set once, at creation.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='registry.importrun')),
                ('pile_cap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='piles', to='registry.pilecap')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('pile_cap', 'label'), name='uniq_pile_label_per_cap')],
            },
        ),
        migrations.AddConstraint(
            model_name='structure',
            constraint=models.UniqueConstraint(fields=('package', 'ref'), name='uniq_structure_ref_per_package'),
        ),
        migrations.AddConstraint(
            model_name='pilecap',
            constraint=models.UniqueConstraint(fields=('structure', 'ref'), name='uniq_pilecap_ref_per_structure'),
        ),
    ]
